### ISSUE TITLE
How to prepare the segmental duplication file for non-human species?

### ISSUE THREAD

**Issue by bampress** [calkan/sonic#11]
I'm doing research on plant species, and I don't have a finished segmental duplication file for it. How can I generate this input file for sonic? Any advice? Many thanks ^_^

**Comment by calkan** [comment]
Hi

try SEDEF: https://www.ncbi.nlm.nih.gov/pubmed/30423092  code: https://github.com/vpc-ccg/sedef

**Comment by bampress** [comment]
ok，I'll have a try. Many thanks for your timely reply!

**Comment by milesandersonmn** [comment]
I am in the same situation, but SEDEF is deprecated. The replacement BISER produces a BEDPE file. Will SONIC accept the BEDPE format?

**Comment by calkan** [comment]
Hi Miles

you can easily convert it to BED with something like

awk '{OFS="\t"; print $1,$2,$3"\n"$4,$5,$6}' biserdups.bedpe | bedtools merge > biserdups.bed
