### ISSUE TITLE
Empty gaps.bed files from some reference genomes (e.g. C. elegans) with no type U or N

### ISSUE THREAD

**Issue by moldach** [calkan/sonic#12]
In step 3, for gap annotations it states we should extract the files from UCSC's `chromAgp.tar.gz` into a folder, merge them and then grep for **component type U or N** (which is in column 5). 

IMO the description for this file by UCSC is lacking; there is no description of what **type U or N** _are_:

> chromAgp.tar.gz - Description of how the assembly was generated from
    fragments, unpacking to one file per chromosome.

From the mouse example I see there are **4 fields**:

```
cat */*|awk '{print $5}' | sort | uniq
F
N
O
W
```

I would like to build a `SONIC` for [_C. elegans_ (WBcel1235)](hgdownload.cse.ucsc.edu/goldenPath/ce11/bigZips/) but there are no **type U or N** to be found (I only see **type F** - what's this?) - resulting in an empty `.bed` file.

What do these mean?

Furthermore, in step 4 for segmental duplication annotations there is a `genomicSuperDups.txt.gz ` file for the mouse genome; however, [I cannot find reference for this in _C. elegans_](http://hgdownload.soe.ucsc.edu/goldenPath/ce11/database/). I will contact UCSC to find out if they have a comparable file for this build.  

My question to you is, in the _absence_ of such file(s). Would there be any harm building SONIC when passing these two empty files (`gaps.bed` & `dups.bed`)?

` sonic --ref ref.fasta --reps reps.out --gaps gaps.bed --dups dups.bed --make-sonic cell.sonic --info "UCSC_WBcel235"`

```
Number of chromosomes: 7
Adding gap intervals to SONIC.
Read 0 BED entries.
Writing entries for chromosome 6
Wrote 0 entries.
Adding segmental duplication intervals to SONIC.
Read 0 BED entries.
Writing entries for chromosome 6
Wrote 0 entries.
Adding 99878 repeats to SONIC.
Read 99857 BED entries.
Writing entries for chromosome 6
Wrote 99857 entries.
Adding GC profile SONIC.
SONIC file cell.sonic is ready.
Memory usage: 31.61 MB.
```

**Comment by calkan** [comment]
no that won't be a problem. The gaps file is merely used to filter out calls that span assembly gaps, certainly an issue in mammalians since those gaps are surrounded by repeats, causing mapping ambiguity. Similar for dups.

**Comment by calkan** [comment]
added this explanation to README. Closing.
